# Generated by Django 4.2 on 2025-07-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('numero_enregistrement', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pharmacie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrationapp.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('disponible', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('prix', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.categorie')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.pharmacie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
