# Generated by Django 4.2 on 2025-07-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='categorie',
        ),
    ]
