# Generated by Django 4.2 on 2025-07-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrationapp', '0002_medicament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacieapp', '0002_remove_medicament_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationapp.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.pharmacie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
    ]
