# Generated by Django 4.2 on 2025-07-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacieapp', '0003_medicamentchoise_delete_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentchoise',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentchoisi', to='pharmacieapp.pharmacie'),
        ),
    ]
