# Generated by Django 4.2 on 2025-07-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrationapp', '0002_medicament'),
        ('pharmacieapp', '0004_alter_medicamentchoise_pharmacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentchoise',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicament', to='administrationapp.medicament'),
        ),
    ]
