# Generated by Django 4.2 on 2025-07-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('numeroenregistrement', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='hopital')),
                ('is_active', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrationapp.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('specialisation', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopitalapp.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopitalapp.choixservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='equipement')),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopitalapp.choixservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identite', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='equipement')),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopitalapp.choixservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choixservice',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopitalapp.hopital'),
        ),
        migrations.AddField(
            model_name='choixservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationapp.service'),
        ),
        migrations.AddField(
            model_name='choixservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
