# Generated by Django 4.2 on 2025-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='numero',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
