# Generated by Django 4.2 on 2025-07-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopitalapp', '0002_docteur_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choixservice',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choixservice', to='hopitalapp.hopital'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='choix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipement', to='hopitalapp.choixservice'),
        ),
        migrations.AlterField(
            model_name='maladie',
            name='choix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maladie', to='hopitalapp.choixservice'),
        ),
    ]
