# Generated by Django 4.2 on 2025-07-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopitalapp', '0003_alter_choixservice_hopital_alter_equipement_choix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='choix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docteur', to='hopitalapp.choixservice'),
        ),
    ]
