# Generated by Django 4.2 on 2025-07-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitalapp', '0004_alter_docteur_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='prix',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='consultation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='photo',
            field=models.ImageField(null=True, upload_to='hopital'),
        ),
    ]
